const appName = "Cryptomask";
const email = "support@yourcryptowallet.com";
const phone = "+91-9876543210";
const address = `${appName} 1234 Elm Street Springfield, IL 62704`;
const facebook = "https://www.facebook.com/johndoe";
const twitter = "https://twitter.com/johndoe";
const linkedin = "https://www.linkedin.com/in/johndoe";

export const contents = {
  common: {
    websiteName: appName,
    playStoreLink:
      "https://play.google.com/store/apps/details?id=io.metamask&hl=en&pli=1",
    appStoreLink:
      "https://apps.apple.com/us/app/metamask-blockchain-wallet/id1438144202",
  },
  homepage: {
    heading: "Your portal to Web3.",
    subHeading:
      "Secure and transfer your assets, swap crypto, trade NFTs, earn yield, and more with the most ease.",
    testimonialMessage: `"This wallet has transformed how I handle my crypto transactions.
              It's fast, reliable, and the transaction fees are incredibly low.
              Whether I'm sending or receiving, the process is always smooth and
              hassle-free."`,
    testimonialName: "- Alex M., Crypto Enthusiast",
    sectionHeading: "Explore wide range of ERC20 Tokens",
    ctaText: "Get the app now!",
    tokens: [
      "./tokens/sub.svg",
      "./tokens/nexxo.svg",
      "./tokens/nft.svg",
      "./tokens/nftb.svg",
      "./tokens/ngc.svg",
      "./tokens/niox.svg",
      "./tokens/nkn.svg",
      "./tokens/nlg.svg",
      "./tokens/nmr.svg",
      "./tokens/noia.svg",
      "./tokens/nos.svg",
      "./tokens/nper.svg",
      "./tokens/npxs.svg",
      "./tokens/nrg.svg",
      "./tokens/nrv.svg",
      "./tokens/nrve.svg",
      "./tokens/ntic.svg",
      "./tokens/ntl.svg",
      "./tokens/ntrn.svg",
      "./tokens/nu.svg",
      "./tokens/nuls.svg",
      "./tokens/nxm.svg",
      "./tokens/nxra.svg",
      "./tokens/sui.svg",
      "./tokens/sun.svg",
      "./tokens/super.svg",
      "./tokens/suqa.svg",
      "./tokens/susd-2.svg",
      "./tokens/susd.svg",
      "./tokens/sushi.svg",
      "./tokens/suter.svg",
      "./tokens/swap.svg",
      "./tokens/sweat.svg",
      "./tokens/sweth.svg",
      "./tokens/swth.svg",
      "./tokens/sxdt.svg",
      "./tokens/sxp.svg",
      "./tokens/syn.svg",
      "./tokens/sys.svg",
      "./tokens/t.svg",
      "./tokens/tbtc-2.svg",
      "./tokens/tbtc.svg",
      "./tokens/tct.svg",
      "./tokens/tel.svg",
      "./tokens/tet.svg",
      "./tokens/tfuel.svg",
      "./tokens/thales.svg",
      "./tokens/thc.svg",
      "./tokens/thedao.svg",
      "./tokens/theta.svg",
      "./tokens/thr.svg",
      "./tokens/tia.svg",
      "./tokens/tio.svg",
      "./tokens/titan.svg",
      "./tokens/tkn.svg",
      "./tokens/tko.svg",
      "./tokens/tky.svg",
      "./tokens/tnb.svg",
      "./tokens/tnc.svg",
      "./tokens/tnd.svg",
      "./tokens/tnt.svg",
      "./tokens/token.svg",
      "./tokens/tomi.svg",
      "./tokens/tomo.svg",
      "./tokens/ton.svg",
      "./tokens/torn.svg",
      "./tokens/tower.svg",
      "./tokens/tpay.svg",
      "./tokens/trac.svg",
      "./tokens/trb.svg",
      "./tokens/tribe.svg",
      "./tokens/trig.svg",
      "./tokens/trtl.svg",
      "./tokens/tru.svg",
      "./tokens/trx.svg",
      "./tokens/tryb.svg",
      "./tokens/ttc.svg",
      "./tokens/tube.svg",
      "./tokens/tusd.svg",
      "./tokens/twt.svg",
      "./tokens/tyzen.svg",
      "./tokens/ubi.svg",
      "./tokens/ubq.svg",
      "./tokens/ubt.svg",
      "./tokens/uft.svg",
      "./tokens/ult-2.svg",
      "./tokens/ult.svg",
      "./tokens/uma.svg",
      "./tokens/uncx.svg",
      "./tokens/unfi.svg",
      "./tokens/uni.svg",
      "./tokens/unibot.svg",
      "./tokens/uniqo.svg",
      "./tokens/unn.svg",
      "./tokens/uos.svg",
      "./tokens/upp.svg",
      "./tokens/usdc.svg",
      "./tokens/usdd.svg",
      "./tokens/usdn.svg",
      "./tokens/usdp.svg",
      "./tokens/usds.svg",
      "./tokens/usdt.svg",
      "./tokens/usx.svg",
      "./tokens/utk.svg",
      "./tokens/uuu.svg",
      "./tokens/uxp.svg",
      "./tokens/vai.svg",
      "./tokens/vgx.svg",
      "./tokens/vsp.svg",
      "./tokens/wabi.svg",
      "./tokens/wbtc.svg",
      "./tokens/weth.svg",
      "./tokens/x2y2.svg",
      "./tokens/zusd.svg",
      "./tokens/nxs.svg",
      "./tokens/nxt.svg",
      "./tokens/oag.svg",
      "./tokens/oax.svg",
      "./tokens/ocean.svg",
      "./tokens/ocn.svg",
      "./tokens/ode.svg",
      "./tokens/ogn.svg",
      "./tokens/ohm.svg",
      "./tokens/oil.svg",
      "./tokens/okb.svg",
      "./tokens/oks.svg",
      "./tokens/olt.svg",
      "./tokens/omg.svg",
      "./tokens/ondo.svg",
      "./tokens/one.svg",
      "./tokens/onion.svg",
      "./tokens/ont.svg",
      "./tokens/op.svg",
      "./tokens/open.svg",
      "./tokens/opium.svg",
      "./tokens/opul.svg",
      "./tokens/opx.svg",
      "./tokens/orai.svg",
      "./tokens/orbs.svg",
      "./tokens/orc.svg",
      "./tokens/orn.svg",
      "./tokens/osmo.svg",
      "./tokens/ost.svg",
      "./tokens/ovc.svg",
      "./tokens/ox.svg",
      "./tokens/oxt.svg",
      "./tokens/pBTC.svg",
      "./tokens/pai.svg",
      "./tokens/paint.svg",
      "./tokens/pal.svg",
      "./tokens/palm-2.svg",
      "./tokens/palm.svg",
      "./tokens/paper.svg",
      "./tokens/par.svg",
      "./tokens/part.svg",
      "./tokens/pasg.svg",
      "./tokens/pax.svg",
      "./tokens/paxg.svg",
      "./tokens/pay.svg",
      "./tokens/pbirb.svg",
      "./tokens/pbr.svg",
      "./tokens/pendle.svg",
      "./tokens/pepe.svg",
      "./tokens/perl.svg",
      "./tokens/perp.svg",
      "./tokens/pha.svg",
      "./tokens/phtk.svg",
      "./tokens/phx.svg",
      "./tokens/pickle.svg",
      "./tokens/pika.svg",
      "./tokens/pip.svg",
      "./tokens/pivx.svg",
      "./tokens/plDAI.svg",
      "./tokens/plUSDC.svg",
      "./tokens/pla.svg",
      "./tokens/play.svg",
      "./tokens/plr.svg",
      "./tokens/pltc.svg",
      "./tokens/pnb.svg",
      "./tokens/png.svg",
      "./tokens/pnk.svg",
      "./tokens/pnt.svg",
      "./tokens/poa.svg",
      "./tokens/poe.svg",
      "./tokens/pokt.svg",
      "./tokens/pols.svg",
      "./tokens/poly-2.svg",
      "./tokens/poly.svg",
      "./tokens/polyx.svg",
      "./tokens/pom.svg",
      "./tokens/pond.svg",
      "./tokens/pool.svg",
      "./tokens/pop.svg",
      "./tokens/powr.svg",
      "./tokens/ppay.svg",
      "./tokens/ppc.svg",
      "./tokens/ppp.svg",
      "./tokens/ppt.svg",
      "./tokens/pre.svg",
      "./tokens/premia.svg",
      "./tokens/prime.svg",
      "./tokens/prl.svg",
      "./tokens/pro.svg",
      "./tokens/prom.svg",
      "./tokens/pros.svg",
      "./tokens/prq.svg",
      "./tokens/psp.svg",
      "./tokens/pst.svg",
      "./tokens/pxp.svg",
      "./tokens/pyr.svg",
      "./tokens/pyth.svg",
      "./tokens/qash.svg",
      "./tokens/qbit.svg",
      "./tokens/qi.svg",
      "./tokens/qkc.svg",
      "./tokens/qlc.svg",
      "./tokens/qnt.svg",
      "./tokens/qrdo.svg",
      "./tokens/qsp.svg",
      "./tokens/qtcon.svg",
      "./tokens/qtum.svg",
      "./tokens/quick.svg",
      "./tokens/r.svg",
      "./tokens/raca.svg",
      "./tokens/rae.svg",
      "./tokens/rai.svg",
      "./tokens/rari.svg",
      "./tokens/ray.svg",
      "./tokens/rbn.svg",
      "./tokens/rbx.svg",
      "./tokens/rcn.svg",
      "./tokens/rdai.svg",
      "./tokens/rdd.svg",
      "./tokens/rdn.svg",
      "./tokens/rdnt.svg",
      "./tokens/ren.svg",
      "./tokens/rep.svg",
      "./tokens/req.svg",
      "./tokens/reth-2.svg",
      "./tokens/reth.svg",
      "./tokens/rev.svg",
      "./tokens/rfox.svg",
      "./tokens/rfwsteth.svg",
      "./tokens/rgt.svg",
      "./tokens/rhoc.svg",
      "./tokens/rif.svg",
      "./tokens/rlc.svg",
      "./tokens/rly.svg",
      "./tokens/rndr.svg",
      "./tokens/rook.svg",
      "./tokens/rose.svg",
      "./tokens/rpl.svg",
      "./tokens/rpx.svg",
      "./tokens/rsr.svg",
      "./tokens/rsv.svg",
      "./tokens/rune.svg",
      "./tokens/rvn.svg",
      "./tokens/s.svg",
      "./tokens/sai.svg",
      "./tokens/salt.svg",
      "./tokens/san.svg",
      "./tokens/sand.svg",
      "./tokens/sapp.svg",
      "./tokens/sar.svg",
      "./tokens/scrl.svg",
      "./tokens/scrt.svg",
      "./tokens/scs.svg",
      "./tokens/sdex.svg",
      "./tokens/sdl.svg",
      "./tokens/sdt.svg",
      "./tokens/seele.svg",
      "./tokens/sefi.svg",
      "./tokens/sei.svg",
      "./tokens/sem.svg",
      "./tokens/seth.svg",
      "./tokens/seth2.svg",
      "./tokens/sfi.svg",
      "./tokens/sfm.svg",
      "./tokens/sfp-2.svg",
      "./tokens/sfp.svg",
      "./tokens/sha.svg",
      "./tokens/shib.svg",
      "./tokens/shr.svg",
      "./tokens/shuf.svg",
      "./tokens/si.svg",
      "./tokens/sia.svg",
      "./tokens/sidus.svg",
      "./tokens/silo.svg",
      "./tokens/skl.svg",
      "./tokens/sky.svg",
      "./tokens/sld.svg",
      "./tokens/slex.svg",
      "./tokens/slp.svg",
      "./tokens/slt.svg",
      "./tokens/smart.svg",
      "./tokens/snail.svg",
      "./tokens/snc.svg",
      "./tokens/sngls.svg",
      "./tokens/snm.svg",
      "./tokens/snt.svg",
      "./tokens/snx.svg",
      "./tokens/soaps.svg",
      "./tokens/socks.svg",
      "./tokens/sofi.svg",
      "./tokens/sol.svg",
      "./tokens/solch.svg",
      "./tokens/soul.svg",
      "./tokens/sov.svg",
      "./tokens/spank.svg",
      "./tokens/spike.svg",
      "./tokens/spn.svg",
      "./tokens/sqr.svg",
      "./tokens/srm.svg",
      "./tokens/ssv.svg",
      "./tokens/stake.svg",
      "./tokens/steem.svg",
      "./tokens/step.svg",
      "./tokens/steth.svg",
      "./tokens/stg.svg",
      "./tokens/stmx.svg",
      "./tokens/storj.svg",
      "./tokens/storm.svg",
      "./tokens/stpt.svg",
      "./tokens/strat.svg",
      "./tokens/strdy.svg",
      "./tokens/strk.svg",
      "./tokens/strx.svg",
      "./tokens/stx.svg",
      "./tokens/stz.svg",
      "./tokens/aave.svg",
      "./tokens/avax.svg",
      "./tokens/enix.svg",
      "./tokens/mom.svg",
      "./tokens/moons.svg",
      "./tokens/mot.svg",
      "./tokens/mpl.svg",
      "./tokens/mta.svg",
      "./tokens/mth.svg",
      "./tokens/mtl.svg",
      "./tokens/mtn.svg",
      "./tokens/mura.svg",
      "./tokens/mvc.svg",
      "./tokens/mvl.svg",
      "./tokens/mvp.svg",
      "./tokens/mwat.svg",
      "./tokens/mwc.svg",
      "./tokens/mxc.svg",
      "./tokens/mxm.svg",
      "./tokens/myb.svg",
      "./tokens/nano.svg",
      "./tokens/nas.svg",
      "./tokens/nav.svg",
      "./tokens/ncash.svg",
      "./tokens/nct.svg",
      "./tokens/near.svg",
      "./tokens/nebl.svg",
      "./tokens/nec.svg",
      "./tokens/neo.svg",
      "./tokens/neox.svg",
      "./tokens/nest.svg",
      "./tokens/new.svg",
      "./tokens/nex.svg",
      "./tokens/nexo.svg",
      "./tokens/nexus.svg",
    ],
  },
  termspage: {
    terms: [
      {
        heading: "Acceptance of Terms",
        details: [
          `By accessing or using ${appName}, you agree to comply with and be bound by these Terms of Service. If you do not agree with these terms, please do not use our Service.`,
        ],
      },
      {
        heading: "Service Description",
        details: [
          `${appName} provides a cryptocurrency wallet application that allows users to manage, store, and transact digital assets securely.`,
        ],
      },
      {
        heading: "User Responsibilities",
        details: [
          "Account Security: You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorized use.",
          "Compliance: You agree to comply with all applicable laws and regulations when using our Service.",
        ],
      },
      {
        heading: "Use of Service",
        details: [
          "Eligibility: You must be at least 12 years old to use our Service. By using our Service, you represent that you meet this age requirement.",
          "Prohibited Activities: You may not use our Service for any illegal activities, including but not limited to fraud, money laundering, or other criminal activities.",
        ],
      },
      {
        heading: "Termination",
        details: [
          "We may suspend or terminate your access to our Service at any time, with or without cause, if we believe you have violated these Terms of Service.",
        ],
      },
    ],
  },
  faqpages: {
    faqs: [
      {
        id: 1,
        question: `What is ${appName}?`,
        answer: `${appName} is a secure and user-friendly cryptocurrency wallet that allows you to store, manage, and transact various digital assets.`,
      },
      {
        id: 2,
        question: "How do I create an account?",
        answer: `To create an account, download our app from the App Store or Google Play, open the app, and follow the on-screen instructions to sign up. You'll need to provide a valid email address and create a strong password.`,
      },
      {
        id: 3,
        question: "How do I secure my wallet?",
        answer:
          "To secure your wallet, enable two-factor authentication (2FA), use a strong and unique password, and regularly update your security settings. Also, make sure to back up your wallet's recovery phrase and store it in a safe place.",
      },
      {
        id: 4,
        question: "How do I send and receive cryptocurrency?",
        answer:
          "To send cryptocurrency, open the app, select the asset you wish to send, enter the recipient's address and the amount, and confirm the transaction. To receive cryptocurrency, share your wallet address with the sender or use the QR code provided in the app.",
      },
      {
        id: 5,
        question: "Can I recover my account if I lose access?",
        answer:
          "Yes, if you lose access to your account, you can recover it using your recovery phrase. During the account setup, you were provided with a recovery phrase. Keep it in a secure place, as it is the only way to restore your wallet if you forget your password or lose your device.",
      },
      {
        id: 6,
        question: `Is ${appName} available on multiple devices?`,
        answer: `Yes, you can access ${appName} on various devices, including smartphones, tablets, and desktops. Simply download the app or visit our website and log in with your account credentials.`,
      },
    ],
  },
  privacypage: {
    privacyPolicies: [
      {
        heading: "Introduction",
        details: [
          `Welcome to ${appName}. We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, and protect your data when you use our crypto wallet services.`,
        ],
      },
      {
        heading: "Information We Collect",
        details: [
          "Personal Information: When you create an account, we may collect personal information such as your name, email address, and phone number.",
          "Usage Data: We collect information on how you interact with our wallet, including transaction history, device information, and IP addresses.",
          "Cookies: We use cookies and similar tracking technologies to enhance your experience on our platform.",
        ],
      },
      {
        heading: "How We Use Your Information",
        details: [
          "To Provide Services: We use your information to operate and maintain your wallet, process transactions, and provide customer support.",
          "To Improve Services: We analyze usage data to understand user behavior and improve our services.",
          "To Communicate: We may send you updates, security alerts, and other notifications related to your use of our services.",
        ],
      },
      {
        heading: "Data Security",
        details: [
          "We implement robust security measures to protect your information from unauthorized access, alteration, disclosure, or destruction. These measures include encryption, firewalls, and secure server environments.",
        ],
      },
      {
        heading: "Sharing Your Information",
        details: [
          "With Your Consent: We may share information with third parties if you have given us explicit consent to do so.",
        ],
      },
    ],
  },
  contactuspage: {
    email,
    phone,
    address,
    facebook,
    twitter,
    linkedin,
  },
};
